import Link from "next/link";
import { PageIntro } from "@/components/site/PageIntro";
import { SiteShell } from "@/components/site/SiteShell";
import { ctaPrimary, ctaSecondary, sectionFrame } from "@/components/site/site-styles";
import { JewelryGrid } from "@/components/gallery/JewelryGrid";
import { FeatureDisabledPage } from "@/features/feature-flags";
import {
  fetchFeatureFlagsServer,
  isFeatureEnabled,
} from "@/lib/feature-flags/server-fetch";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "Demo jewelry · MIST Studio",
};

export default async function GalleryPage() {
  const flags = await fetchFeatureFlagsServer();
  if (!isFeatureEnabled(flags, "gallery")) {
    return <FeatureDisabledPage title="Gallery unavailable" />;
  }
  return (
    <SiteShell>
      <section className={`${sectionFrame} pb-14 pt-20 sm:pt-28`}>
        <PageIntro
          kicker="Gallery · Archive"
          title="Objects,"
          titleItalic="built by the kernel."
          lead="Every piece is generated by the MIST CAD kernel: real heads, seated stones, watertight bands. Open one as a real-time studio scene, or customise it — cut, carat, metal, size — in the designer."
        >
          <div className="flex flex-wrap gap-3">
            <Link href="/design" className={ctaPrimary}>
              Design your own
            </Link>
            <Link href="/stones" className={ctaSecondary}>
              Browse the cuts
            </Link>
          </div>
        </PageIntro>
      </section>
      <section className={`${sectionFrame} pb-28`}>
        <JewelryGrid />
      </section>
    </SiteShell>
  );
}
