export type GemConfig = {
  ior: number;
  dispersionBase: number;
  dispersionAmplitude: number;
  roughness: number;
  thickness: number;
  envMapIntensity: number;
  baseColor: string;
  attenuationColor: string;
  attenuationDistance: number;
  /** 0..1 — 1 is fully transmissive (glassy). Pearl/opal/jade reduce this. */
  transmission?: number;
  /** Optional iridescence (pearl, opal). */
  iridescence?: number;
  /** Optional clearcoat (high-polish gems). */
  clearcoat?: number;
};

/**
 * IOR and dispersion values are physically accurate per standard gemology references.
 * Dispersion `base` is bumped above the natural value for diamond/moissanite to give visible
 * spectral fire on screen (Three.js dispersion is an approximation; small natural values barely show).
 */
export const GEM_CONFIGS = {
  diamond: {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#ffffff",
    attenuationColor: "#ffffff",
    attenuationDistance: 0.4,
    clearcoat: 0.6,
  },
  moissanite: {
    ior: 2.65,
    dispersionBase: 0.12,
    dispersionAmplitude: 0.05,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.7,
    baseColor: "#ffffff",
    attenuationColor: "#fbfaf5",
    attenuationDistance: 0.4,
    clearcoat: 0.7,
  },
  zircon: {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#ffffff",
    attenuationColor: "#f0f4ff",
    attenuationDistance: 0.45,
  },
  ruby: {
    ior: 1.77,
    dispersionBase: 0.025,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#E0115F",
    attenuationColor: "#FF1F5A",
    attenuationDistance: 0.45,
    clearcoat: 0.4,
  },
  sapphire: {
    ior: 1.77,
    dispersionBase: 0.025,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#0F52BA",
    attenuationColor: "#1E3FFF",
    attenuationDistance: 0.45,
    clearcoat: 0.4,
  },
  spinel: {
    ior: 1.72,
    dispersionBase: 0.026,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.45,
    baseColor: "#FF3F4E",
    attenuationColor: "#FF5A6A",
    attenuationDistance: 0.5,
    clearcoat: 0.35,
  },
  tanzanite: {
    ior: 1.7,
    dispersionBase: 0.034,
    dispersionAmplitude: 0.012,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.45,
    baseColor: "#4B3FA7",
    attenuationColor: "#7958FF",
    attenuationDistance: 0.5,
    clearcoat: 0.3,
  },
  "garnet-tsavorite": {
    ior: 1.74,
    dispersionBase: 0.031,
    dispersionAmplitude: 0.012,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.45,
    baseColor: "#1FAE5A",
    attenuationColor: "#2BD16A",
    attenuationDistance: 0.5,
    clearcoat: 0.3,
  },
  "garnet-almandine": {
    ior: 1.79,
    dispersionBase: 0.028,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.45,
    baseColor: "#7A1F2D",
    attenuationColor: "#A82037",
    attenuationDistance: 0.5,
    clearcoat: 0.3,
  },
  peridot: {
    ior: 1.66,
    dispersionBase: 0.024,
    dispersionAmplitude: 0.009,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#9FCC2D",
    attenuationColor: "#C6E663",
    attenuationDistance: 0.55,
  },
  "topaz-blue": {
    ior: 1.62,
    dispersionBase: 0.018,
    dispersionAmplitude: 0.008,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#88D8E0",
    attenuationColor: "#B6ECF0",
    attenuationDistance: 0.6,
  },
  tourmaline: {
    ior: 1.62,
    dispersionBase: 0.021,
    dispersionAmplitude: 0.009,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#FF49A0",
    attenuationColor: "#FF6FB7",
    attenuationDistance: 0.55,
  },
  aquamarine: {
    ior: 1.58,
    dispersionBase: 0.017,
    dispersionAmplitude: 0.007,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#7FE0E8",
    attenuationColor: "#BFEFF3",
    attenuationDistance: 0.65,
  },
  emerald: {
    ior: 1.58,
    dispersionBase: 0.02,
    dispersionAmplitude: 0.008,
    roughness: 0.03,
    thickness: 0.55,
    envMapIntensity: 1.35,
    baseColor: "#1ABC57",
    attenuationColor: "#7FDBA7",
    attenuationDistance: 0.5,
  },
  morganite: {
    ior: 1.58,
    dispersionBase: 0.017,
    dispersionAmplitude: 0.007,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#FFCBC4",
    attenuationColor: "#FFE4DD",
    attenuationDistance: 0.7,
  },
  amethyst: {
    ior: 1.55,
    dispersionBase: 0.016,
    dispersionAmplitude: 0.007,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#9966CC",
    attenuationColor: "#B388E6",
    attenuationDistance: 0.55,
  },
  citrine: {
    ior: 1.55,
    dispersionBase: 0.016,
    dispersionAmplitude: 0.007,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#E4C04A",
    attenuationColor: "#FFE08A",
    attenuationDistance: 0.6,
  },
  opal: {
    ior: 1.45,
    dispersionBase: 0.025,
    dispersionAmplitude: 0.015,
    roughness: 0.18,
    thickness: 0.55,
    envMapIntensity: 1.3,
    baseColor: "#F5F0E6",
    attenuationColor: "#FFE9D6",
    attenuationDistance: 0.4,
    transmission: 0.5,
    iridescence: 0.9,
  },
  jade: {
    ior: 1.66,
    dispersionBase: 0.014,
    dispersionAmplitude: 0.006,
    roughness: 0.18,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#52B788",
    attenuationColor: "#74C69D",
    attenuationDistance: 0.35,
    transmission: 0.55,
  },
  pearl: {
    ior: 1.53,
    dispersionBase: 0.012,
    dispersionAmplitude: 0.005,
    roughness: 0.35,
    thickness: 0.4,
    envMapIntensity: 1.0,
    baseColor: "#F8F1E6",
    attenuationColor: "#FFFAF0",
    attenuationDistance: 0.3,
    transmission: 0.0,
    iridescence: 0.7,
  },
  "diamond-canary": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#FFE066",
    attenuationColor: "#FFDB4D",
    attenuationDistance: 0.45,
    clearcoat: 0.6,
  },
  "diamond-pink": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#FFB1C8",
    attenuationColor: "#FF80AB",
    attenuationDistance: 0.5,
    clearcoat: 0.6,
  },
  "diamond-blue": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#88BFE0",
    attenuationColor: "#4FA3D1",
    attenuationDistance: 0.5,
    clearcoat: 0.6,
  },
  "diamond-cognac": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.55,
    baseColor: "#8E5A2B",
    attenuationColor: "#6B3F1E",
    attenuationDistance: 0.35,
    clearcoat: 0.6,
  },
  "diamond-champagne": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#E8C68A",
    attenuationColor: "#D9B26E",
    attenuationDistance: 0.5,
    clearcoat: 0.6,
  },
  "diamond-black": {
    ior: 2.417,
    dispersionBase: 0.05,
    dispersionAmplitude: 0.02,
    roughness: 0.06,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#1a1a1a",
    attenuationColor: "#0a0a0a",
    attenuationDistance: 0.15,
    clearcoat: 0.7,
  },
  "diamond-d-colorless": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#ffffff",
    attenuationColor: "#ffffff",
    attenuationDistance: 0.4,
    clearcoat: 0.6,
  },
  "diamond-h-nearcolorless": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#fdfdfb",
    attenuationColor: "#fbfbf5",
    attenuationDistance: 0.42,
    clearcoat: 0.6,
  },
  "diamond-k-faintyellow": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#fff8e6",
    attenuationColor: "#fff0cc",
    attenuationDistance: 0.45,
    clearcoat: 0.6,
  },
  "diamond-p-verylightyellow": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#fff2cc",
    attenuationColor: "#ffe8a8",
    attenuationDistance: 0.5,
    clearcoat: 0.6,
  },
  "diamond-t-lightyellow": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#ffeeb3",
    attenuationColor: "#ffe08a",
    attenuationDistance: 0.5,
    clearcoat: 0.6,
  },
  "diamond-green": {
    ior: 2.417,
    dispersionBase: 0.08,
    dispersionAmplitude: 0.035,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.6,
    baseColor: "#BFE6C2",
    attenuationColor: "#8FD49A",
    attenuationDistance: 0.5,
    clearcoat: 0.6,
  },
  "sapphire-pink": {
    ior: 1.77,
    dispersionBase: 0.025,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#E58FB0",
    attenuationColor: "#FF7FB0",
    attenuationDistance: 0.45,
    clearcoat: 0.4,
  },
  "sapphire-yellow": {
    ior: 1.77,
    dispersionBase: 0.025,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#E9C84A",
    attenuationColor: "#FFD96B",
    attenuationDistance: 0.45,
    clearcoat: 0.4,
  },
  "sapphire-green": {
    ior: 1.77,
    dispersionBase: 0.025,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#4FAE84",
    attenuationColor: "#6BD1A0",
    attenuationDistance: 0.45,
    clearcoat: 0.4,
  },
  "sapphire-padparadscha": {
    ior: 1.77,
    dispersionBase: 0.025,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#FF9E76",
    attenuationColor: "#FFB893",
    attenuationDistance: 0.45,
    clearcoat: 0.4,
  },
  "garnet-rhodolite": {
    ior: 1.76,
    dispersionBase: 0.028,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#9B2D52",
    attenuationColor: "#C13E6E",
    attenuationDistance: 0.5,
    clearcoat: 0.3,
  },
  "tourmaline-green": {
    ior: 1.62,
    dispersionBase: 0.021,
    dispersionAmplitude: 0.009,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#3FAE5A",
    attenuationColor: "#6BD17F",
    attenuationDistance: 0.55,
  },
  "tourmaline-rubellite": {
    ior: 1.62,
    dispersionBase: 0.021,
    dispersionAmplitude: 0.009,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#E0245E",
    attenuationColor: "#FF4E80",
    attenuationDistance: 0.55,
  },
  "quartz-smoky": {
    ior: 1.55,
    dispersionBase: 0.016,
    dispersionAmplitude: 0.007,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.3,
    baseColor: "#6B4E36",
    attenuationColor: "#8A6A4A",
    attenuationDistance: 0.4,
  },
  "quartz-rose": {
    ior: 1.55,
    dispersionBase: 0.016,
    dispersionAmplitude: 0.007,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.3,
    baseColor: "#F4B8C4",
    attenuationColor: "#FAD2DA",
    attenuationDistance: 0.5,
    transmission: 0.7,
  },
  "zircon-blue": {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#5FC8E0",
    attenuationColor: "#8FE0F0",
    attenuationDistance: 0.45,
  },
  "zircon-green": {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#6FBE5A",
    attenuationColor: "#9FD98A",
    attenuationDistance: 0.45,
  },
  "zircon-red": {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#C0392B",
    attenuationColor: "#E0594B",
    attenuationDistance: 0.45,
  },
  "zircon-yellow": {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#E9C84A",
    attenuationColor: "#FFD96B",
    attenuationDistance: 0.45,
  },
  "zircon-brown": {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#8A5E3C",
    attenuationColor: "#A87E5A",
    attenuationDistance: 0.4,
  },
  "zircon-cinnamon": {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#B5642C",
    attenuationColor: "#D9854B",
    attenuationDistance: 0.4,
  },
  "zircon-turquoise": {
    ior: 1.93,
    dispersionBase: 0.045,
    dispersionAmplitude: 0.015,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#40C4B0",
    attenuationColor: "#6FE0CE",
    attenuationDistance: 0.45,
  },
  "cabochon-amethyst": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#9966CC",
    attenuationColor: "#B388E6",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "cabochon-emerald": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#1ABC57",
    attenuationColor: "#7FDBA7",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "cabochon-ruby": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#E0115F",
    attenuationColor: "#FF1F5A",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "cabochon-sapphire": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#0F52BA",
    attenuationColor: "#1E3FFF",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "cabochon-sapphire-yellow": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#E9C84A",
    attenuationColor: "#FFD96B",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "cabochon-topaz": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#88D8E0",
    attenuationColor: "#B6ECF0",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "onyx-black": {
    ior: 1.5,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.25,
    thickness: 0.55,
    envMapIntensity: 1.0,
    baseColor: "#0E0E10",
    attenuationColor: "#0E0E10",
    attenuationDistance: 0.1,
    transmission: 0.0,
  },
  "lapis-lazuli": {
    ior: 1.5,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.25,
    thickness: 0.55,
    envMapIntensity: 1.0,
    baseColor: "#26418F",
    attenuationColor: "#26418F",
    attenuationDistance: 0.1,
    transmission: 0.0,
  },
  turquoise: {
    ior: 1.5,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.25,
    thickness: 0.55,
    envMapIntensity: 1.0,
    baseColor: "#40C4B0",
    attenuationColor: "#40C4B0",
    attenuationDistance: 0.1,
    transmission: 0.0,
  },
  malachite: {
    ior: 1.5,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.25,
    thickness: 0.55,
    envMapIntensity: 1.0,
    baseColor: "#1F6E5A",
    attenuationColor: "#1F6E5A",
    attenuationDistance: 0.1,
    transmission: 0.0,
  },
  "spinel-blue": {
    ior: 1.72,
    dispersionBase: 0.026,
    dispersionAmplitude: 0.01,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.5,
    baseColor: "#3A6AD0",
    attenuationColor: "#5A8AF0",
    attenuationDistance: 0.5,
    clearcoat: 0.4,
  },
  "spinel-black": {
    ior: 1.72,
    dispersionBase: 0.02,
    dispersionAmplitude: 0.008,
    roughness: 0.04,
    thickness: 0.55,
    envMapIntensity: 1.3,
    baseColor: "#1A1A1E",
    attenuationColor: "#0A0A0C",
    attenuationDistance: 0.2,
    clearcoat: 0.5,
  },
  alexandrite: {
    ior: 1.75,
    dispersionBase: 0.028,
    dispersionAmplitude: 0.012,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.45,
    baseColor: "#4A8A6A",
    attenuationColor: "#6AB08A",
    attenuationDistance: 0.5,
    clearcoat: 0.35,
  },
  chrysoberyl: {
    ior: 1.75,
    dispersionBase: 0.028,
    dispersionAmplitude: 0.012,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.45,
    baseColor: "#D8E060",
    attenuationColor: "#E8F080",
    attenuationDistance: 0.55,
    clearcoat: 0.3,
  },
  kunzite: {
    ior: 1.66,
    dispersionBase: 0.022,
    dispersionAmplitude: 0.009,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.35,
    baseColor: "#E8B8D8",
    attenuationColor: "#F0C8E8",
    attenuationDistance: 0.6,
  },
  iolite: {
    ior: 1.55,
    dispersionBase: 0.02,
    dispersionAmplitude: 0.008,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.35,
    baseColor: "#5A5A9A",
    attenuationColor: "#7A7AB8",
    attenuationDistance: 0.5,
  },
  sunstone: {
    ior: 1.54,
    dispersionBase: 0.018,
    dispersionAmplitude: 0.008,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.3,
    baseColor: "#E8A060",
    attenuationColor: "#F0C080",
    attenuationDistance: 0.55,
    iridescence: 0.4,
  },
  "topaz-imperial": {
    ior: 1.62,
    dispersionBase: 0.018,
    dispersionAmplitude: 0.008,
    roughness: 0.02,
    thickness: 0.55,
    envMapIntensity: 1.4,
    baseColor: "#E8A040",
    attenuationColor: "#F0C060",
    attenuationDistance: 0.55,
  },
  "emerald-colombian": {
    ior: 1.58,
    dispersionBase: 0.02,
    dispersionAmplitude: 0.008,
    roughness: 0.04,
    thickness: 0.55,
    envMapIntensity: 1.35,
    baseColor: "#0E9A48",
    attenuationColor: "#4AC878",
    attenuationDistance: 0.45,
  },
  "pearl-tahitian": {
    ior: 1.53,
    dispersionBase: 0.012,
    dispersionAmplitude: 0.005,
    roughness: 0.35,
    thickness: 0.55,
    envMapIntensity: 1.0,
    baseColor: "#3A4A4A",
    attenuationColor: "#5A6A6A",
    attenuationDistance: 0.3,
    transmission: 0.0,
    iridescence: 0.8,
  },
  "pearl-golden": {
    ior: 1.53,
    dispersionBase: 0.012,
    dispersionAmplitude: 0.005,
    roughness: 0.32,
    thickness: 0.55,
    envMapIntensity: 1.05,
    baseColor: "#E8C880",
    attenuationColor: "#F0D8A0",
    attenuationDistance: 0.35,
    transmission: 0.0,
    iridescence: 0.65,
  },
  "cabochon-garnet": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#7A1F2D",
    attenuationColor: "#A82037",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "cabochon-citrine": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#E4C04A",
    attenuationColor: "#FFE08A",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "cabochon-morganite": {
    ior: 1.55,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.12,
    thickness: 0.55,
    envMapIntensity: 1.1,
    baseColor: "#FFCBC4",
    attenuationColor: "#FFE4DD",
    attenuationDistance: 0.25,
    transmission: 0.2,
  },
  "jade-dark": {
    ior: 1.5,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.25,
    thickness: 0.55,
    envMapIntensity: 1.0,
    baseColor: "#2A6A4A",
    attenuationColor: "#2A6A4A",
    attenuationDistance: 0.1,
    transmission: 0.0,
  },
  "agate-fire": {
    ior: 1.5,
    dispersionBase: 0.0,
    dispersionAmplitude: 0.0,
    roughness: 0.25,
    thickness: 0.55,
    envMapIntensity: 1.0,
    baseColor: "#C86040",
    attenuationColor: "#C86040",
    attenuationDistance: 0.1,
    transmission: 0.0,
  },
} satisfies Record<string, GemConfig>;

/** All catalog gem slugs with renderer-ready optical params (≥ 65 entries). */
export type GemPresetId = keyof typeof GEM_CONFIGS;

export const GEM_PRESET_IDS = Object.keys(GEM_CONFIGS) as GemPresetId[];

export function isGemPresetId(id: string): id is GemPresetId {
  return Object.prototype.hasOwnProperty.call(GEM_CONFIGS, id);
}
